# generated at 2026-05-09T17:19:21.702020+00:00
from __future__ import annotations
from typing import Any
from C:\Users\nicho\Documents\Unreal Projects\Starcel9\Content\Scripts\cli import CommandResult

def bash(*args: str) -> CommandResult: ...
def cmd(*args: str) -> CommandResult: ...
def es(*args: str) -> CommandResult: ...
def powershell(*args: str) -> CommandResult: ...
def ps(*args: str) -> CommandResult: ...
def search_system(*args: str) -> CommandResult: ...

